<?php
namespace Tenweb_Builder;

include_once 'base.php';

class SlideTemplate extends BaseTemplate {

	public static function get_slug(){
		return "twbb_slide";
	}

	public static function get_title(){
		return 'Slide';
	}


	public function save_type(){
		parent::save_type(); // TODO: Change the autogenerated stub

		if(!empty($_REQUEST['twbb-template-post-type'])) {
			$meta_value = sanitize_text_field($_REQUEST['twbb-template-post-type']);
			$this->update_meta('_twbb-template-post-type', $meta_value);
		}

	}

	public static function print_twbb_template($template_id, $templates = "") {
		self::print_builder_content($template_id);
	}

}
